import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingTop: 10,
    paddingHorizontal: 10,
    backgroundColor: '#FFF',
  },
  SafeAreaView1: { backgroundColor: '#FFF', flex: 0 },
  SafeAreaView2: { flex: 1, backgroundColor: '#FFF', width: '100%' },
  outerWrapper: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingTop: 36,
    width: '100%',
    paddingBottom: 72,
  },
  buttonStyle: {
    backgroundColor: '#EEE',
    paddingHorizontal: 40,
    paddingVertical: 30,
    borderWidth: 0.5,
    borderColor: '#F0F0F0',
    borderRadius: 10,
  },
  text: {
    fontSize: 14,
    color: '#207198',
    fontWeight: 'normal',
    textAlign: 'left',
    paddingLeft: 4,
  },
  inputField: {
    borderColor: '#207198',
    borderWidth: 2,
    borderRadius: 6,
    width: '100%',
    fontSize: 16,
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  pickerSelect: {
    borderColor: '#207198',
    borderWidth: 2,
    borderRadius: 6,
    width: '100%',
    fontSize: 16,
  },
  errorText: {
    color: 'red',
    fontSize: 12,
    fontWeight: '300',
    textAlign: 'left',
    paddingLeft: 4,
  },
  formView: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    paddingBottom: 12,
  },
  submitButton: {
    width: '100%',
    backgroundColor: '#FB724C',
    fontSize: 18,
    fontWeight: 'bold',
    padding: 12,
    textAlign: 'center',
    color: '#FFF',
    borderRadius: 12,
  },
  pressedButton: {
    backgroundColor: '#FE904B',
  },
  pageTitle: {
    color: '#0E4A67',
    fontSize: 32,
    fontWeight: 'bold',
    paddingBottom: 12,
  },
  switchView: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 4,
  },
  switchText: {
    color: '#FE904B',
  },
  tableHead: { height: 70, backgroundColor: '#f1f8ff' },
  tableContainer: {
    flex: 1,
    padding: 16,
    paddingTop: 30,
    backgroundColor: '#fff',
  },
  tableText: { margin: 2, textAlign: 'center' },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'stretch',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    height: 250,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
  },
  selectedRow: {
    backgroundColor: '#00affb',
  },
});
